version: "3"

services:
    php:
        build:
            dockerfile: docker/php/Dockerfile
        container_name: demo_places_backend_php
        networks:
            - default
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ~/.gitconfig:/root/.gitconfig:ro
        working_dir: /var/www/html

    composer:
        build:
            dockerfile: docker/php/Dockerfile
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
        container_name: demo_places_backend_composer
        depends_on:
            - php
        entrypoint: composer
        networks:
            - default
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ~/.gitconfig:/root/.gitconfig:ro
        working_dir: /var/www/html

    symfony:
        build:
            dockerfile: docker/php/Dockerfile
        container_name: demo_places_backend_symfony
        depends_on:
            - php
            - database
        entrypoint: symfony
        networks:
            - default
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ~/.gitconfig:/root/.gitconfig:ro
        working_dir: /var/www/html

    web:
        build:
            dockerfile: docker/php/Dockerfile
        container_name: demo_places_backend_web
        depends_on:
            - php
            - database
        labels:
            traefik.enable: true
            traefik.docker.network: local_environment_web
            traefik.http.routers.demo_places_backend_web.tls: true
            traefik.http.routers.demo_places_backend_web.rule: HostRegexp(`demo-places{ip:(\.[0-9]{3}\.[0-9]{3}\.[0-9]{1}\.[0-9]{2,3})?}.traefik.me`)
            traefik.http.routers.demo_places_backend_web.tls.domains[0].main: "demo-places.traefik.me"
            traefik.http.routers.demo_places_backend_web.tls.domains[0].sans: "demo-places-*.traefik.me"
        networks:
            - default
            - local_environment_web
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ~/.gitconfig:/root/.gitconfig:ro
        working_dir: /var/www/html

    database:
        container_name: demo_places_backend_database
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
            POSTGRES_DB: demo_places
        image: postgres:15
        networks:
            - default
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ~/.gitconfig:/root/.gitconfig:ro

    adminer:
        container_name: demo_places_backend_adminer
        depends_on:
            - database
        image: adminer
        labels:
            traefik.enable: true
            traefik.docker.network: local_environment_web
            traefik.http.routers.demo_places_backend_adminer.tls: true
            traefik.http.routers.demo_places_backend_adminer.rule: HostRegexp(`database-demo-places{ip:(\.[0-9]{3}\.[0-9]{3}\.[0-9]{1}\.[0-9]{2,3})?}.traefik.me`)
            traefik.http.routers.demo_places_backend_adminer.tls.domains[0].main: "database-demo-places.traefik.me"
            traefik.http.routers.demo_places_backend_adminer.tls.domains[0].sans: "database-demo-places-*.traefik.me"
            traefik.http.services.demo_places_backend_adminer.loadbalancer.server.port: "8080"
        networks:
            - default
            - local_environment_web
        restart: unless-stopped

    mailer:
        container_name: demo_places_backend_mailer
        image: maildev/maildev
        labels:
            traefik.enable: true
            traefik.docker.network: local_environment_web
            traefik.http.routers.demo_places_backend_mailer.tls: true
            traefik.http.routers.demo_places_backend_mailer.rule: HostRegexp(`mailer-demo-places{ip:(\.[0-9]{3}\.[0-9]{3}\.[0-9]{1}\.[0-9]{2,3})?}.traefik.me`)
            traefik.http.routers.demo_places_backend_mailer.tls.domains[0].main: "mailer-demo-places.traefik.me"
            traefik.http.routers.demo_places_backend_mailer.tls.domains[0].sans: "mailer-demo-places-*.traefik.me"
            traefik.http.services.demo_places_backend_mailer.loadbalancer.server.port: "1080"
        networks:
            - default
            - local_environment_web
        restart: unless-stopped

volumes:
    postgres_data:

networks:
    default:
        driver: bridge
    local_environment_web:
        external: true
